language: node_js
node_js:
  - "6"
  - "8"
after_script:
- npm run coveralls
deploy:
  provider: npm
  email: web-human@w3.org
  api_key:
    secure: ft4F0o6xd33U6YT94BBZ3X2u5kCW6Y3AUR/Td4vklfnZK9ogZONR88igEQUIA7nD9+xuYTK/OvmbIuNml60lO3VJM4WE0Q0khQrlOa9Fz5aga+JLGZEknSqjN6iCP7gXJaPOyejAV9KpFfOP6SLEuquN4sG4zkIwLWS4F+HKiFM=
  on:
    tags: true
    repo: w3c/insafe
